server:
  port: 9000
  netty:
    connection-timeout: 2s # How long to wait for TCP connection
    idle-timeout: 15s # How long to wait before closing TCP connection if no data
  shutdown: graceful

spring:
  application:
    name: api-gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s # grace period
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        multiplier: 1.1
        initial-interval: 1000
        max-interval: 2000
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic # elastic, fixed or disabled
          max-idle-time: 15s # Idle time after which communication channel closes
          max-life-time: 60s # Time after which communication channel closes
      default-filters:
        - SaveSession # Save session data in the store before forwarding the request to the downstream
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR # (When the error is 5xx)
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException # Only when these exceptions are thrown
            backoff:
              firstBackoff: 500ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1

      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalog-fallback
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
        - id: spa-route
          uri: ${SPA_URL:http://localhost:9004}
          predicates:
            - Path=/,/*.css,/*.js,/favicon.ico
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: polar-keycloak-secret
            scope: openid # Similar to role for users (but for application instead)
        provider:
          keycloak:
            issuer-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI:http://localhost:8080}/realms/PolarBookshop


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
logging:
  level:
    io.github.resilience4j: DEBUG