server:
  port: 9000
  netty:
    connection-timeout: 2s # How long to wait for TCP connection
    idle-timeout: 15s # How long to wait before closing TCP connection if no data
  shutdown: graceful

spring:
  application:
    name: edge-service
  lifecycle:
    timeout-per-shutdown-phase: 15s # grace period
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic # elastic, fixed or disabled
          max-idle-time: 15s # Idle time after which communication channel closes
          max-life-time: 60s # Time after which communication channel closes

      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
          predicates:
            - Path=/books/**
        - id: order-route
          uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
          predicates:
            - Path=/orders/**